#!/bin/bash
sudo apt-get update && sudo apt-get install -y --no-install-recommends ca-certificates wget curl node-less postgresql-9.5 postgresql-server-dev-9.5 build-essential python3-pillow python3-lxml python-ldap3 python3-dev python3-pip python3-setuptools npm nodejs git libldap2-dev libsasl2-dev libxml2-dev libxslt1-dev libjpeg-dev zlib1g-dev npm libfontconfig1
sudo npm install -g less less-plugin-clean-css phantomjs -y && ln -s /usr/bin/nodejs /usr/bin/node
curl -o wkhtmltox.deb -SL http://nightly.odoo.com/extra/wkhtmltox-0.12.1.2_linux-jessie-amd64.deb
echo '40e8b906de658a2221b15e4e8cd82565a47d7ee8 wkhtmltox.deb' | sha1sum -c -
sudo dpkg --force-depends -i wkhtmltox.deb
sudo apt-get -y install -f --no-install-recommends
wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz && sudo gunzip GeoLiteCity.dat.gz && sudo mkdir /usr/share/GeoIP/ && sudo mv GeoLiteCity.dat /usr/share/GeoIP/
sudo su - postgres -c "createuser -s flectra"
echo `pwd`
ls -alh .
env
