#!/bin/bash
echo "Activating Python Environment ---->"
sudo su - travis -c "source ~/virtualenv/python3.6.3/bin/activate "
echo "Creating a database with Base Module ---->"
sudo su - travis -c "/home/travis/build/flectrahq/flectra/flectra-bin --addons-path=/home/travis/build/flectrahq/flectra/addons --stop-after-init -d base -i base --log-file=~/flectra-base.log"
echo "Creating a database with All Modules ---->"
sudo su - travis -c "/home/travis/build/flectrahq/flectra/flectra-bin --addons-path=/home/travis/build/flectrahq/flectra/addons --stop-after-init -d all -i 'all' --log-file=~/flectra-all.log"
exit 0
